### PR TITLE
APPL-73 - Split out Version Comparison

### PR DESCRIPTION
**Pull request by mplanchard**
Opened up the project, uploaded to PyPi, etc.

### CODE REVIEW

**Comment by jknightihiji** [comment]
I see that your aren't really throwing errors based on unexpected output. It would be a nice feature in the event that the version string isn't recognized. I'll take a look at adding that in.

**Comment by mplanchard** [comment]
Yeah, it's still fairly alpha-ish.

**Comment by mplanchard** [comment]
I'll definitely put that in for the next PR, though, along with an errors.py and at least one custom error class.

**Comment by mplanchard** [comment]
Went ahead and threw an error if the initial parsing fails. As long as that succeeds, the other methods should work, due to the (relatively) standardized nature of RPM package strings.

**Comment by jknightihiji** [comment]
I'm getting an error while running nose with python2.7. 

(test)dontworryboutit:version_utils root# nosetests

# E

## ERROR: Failure: ImportError (No module named mock)

Traceback (most recent call last):
  File "/tmp/test/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/tmp/test/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/tmp/test/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/private/tmp/version_utils/tests/test_rpm.py", line 10, in <module>
    from unittest.mock import MagicMock, patch
ImportError: No module named mock

---

Ran 1 test in 0.003s

I resolved it by installing unittest2. Did I miss something in the documentation about requirements to run tests?

**Comment by jknightihiji** [comment]
All tests pass. Looks good! Ship it.

**Comment by mplanchard** [comment]
I'll look into the unittest thing. Thanks!

**Pull request merged**
